obj-y +=  printf.o idt.o interrupt.o trap.o process.o  task0.o task0_main.o pid.o system_call.o fork.o system_call_func.o kernel.o serial.o schedule.o refcount.o
obj-y += fault/

EXTRA_LDFLAGS +=  -T link.lds